### ISSUE TITLE
Is firebase cli in dockerfile up to date?

### ISSUE THREAD

**Issue by aelamran** [mickfeech/firestore-emulator-action#3]
Hi there,

I am wondering if the firebase cli used in the dockerfile is up to date? 
I noticed a difference behaviour between the github action CI when running tests compared to the emulator I use locally.

If not up to date, can you please take care of it?

**Comment by mickfeech** [comment]
Just ran a new build with the latest emulator.  Let me know if this resolves your issue.

**Comment by mickfeech** [comment]
Asserting closure, if continues to be a problem please open another issue.

**Comment by aelamran** [comment]
I think it's good now, thank you @mickfeech
